### ISSUE TITLE
v3.4 Custom logfile for agent e.g. /var/log/logdna-agent.log rather than /var/log/syslog

### ISSUE THREAD

**Issue by Piponater** [logdna/logdna-agent-v2#331]
In Linux(ubuntu), the new rust agent seems to only write its logs to /var/log/syslog, unlike the previous node version which had its own log file /var/log/logdna-agent.log. Is there any way to override this behavior/specify for the agent's run logs to be sent to another file? The new agent is quite verbose and can make the Syslog quite inconvenient to read when it's swamped in areas by the agent's log output.

**Comment by c-nixon** [comment]
Hi,

The newer linux agent lets Systemd managing it's log files, Ubuntu must configure the things such that the journald logs are forwarded to /var/log/syslog.

You can override that behaviour in systemd by editing the agent's systemd unit file. You can do that using

If you do the following the agents logs should be sent to their own file rather than journald :
* Run the following to open your $EDITOR the current agent systemd unit configuration.
`systemctl edit --full logdna-agent.service`
* Add the following lines
```
StandardOutput=append:/var/log/logdna-agent.log
StandardError=append:/var/log/logdna-agent.log
```
* Save and exit your editor 
* Run the following to refresh the systemd configuration and restart the agent service
`systemctl daemon-reload && systemctl restart logdna-agent`

**Comment by Piponater** [comment]
Thanks for the help, this worked for me.
