### ISSUE TITLE
application logs

### ISSUE THREAD

**Issue by danikostyal** [logdna/logdna-agent-v2#52]
Hi! We are trying to use the IBM Log Analysis with LogDNA to gather logs from some MobileFirst pods running in the IBM Kubernetes Service. We are having trouble get LogDNA service to read the application logs which are held in /opt/ibm/wlp/usr/servers/mfp/logs/ path. We added  the LOGDNA_LOG_DIRS variable but still no luck. The MobileFirst app sends logs only to file, not to STDOUT. Is this the problem? Any help is much appreciated.

**Comment by jakedipity** [comment]
That would probably be the cleanest workaround for your case. It should work since you're still relying on Kubernetes to handle log management which means the logs will end up in the correct place for the agent to ingest. The only thing that might be different is the container metadata we collect from the logs; the logs will have the metadata for the sidecar container as opposed to the main container.

The documentation there seems to provide a good starting place for this approach. We'll make this complete for now, but let us know if it works or not. If not we can think of something else!
